// 基于 list.txt 自动生成的图片索引 
const imageFiles = [
    "001-Apollo 11 stones.jpg",
    "002-Great Hall of the Bulls.jpg",
    "003-Camelid sacrum.jpg",
    "004-Running horned woman.jpg",
    "005-Beaker with ibex motifs.jpg",
    "006-Anthropomorphic stele.jpg",
    "007-Jade cong.jpg",
    "008-Stonehenge-1.jpg",
    "008-Stonehenge-2.jpg",
    "009-The Ambum Stone.jpg",
    "010-Tlatilco female figurine.jpg",
    "011-Terra cotta fragment.jpg",
    "012-White Temple and ziggurat.jpg",
    "012-White Temple.jpg",
    "013-Palette of King Narmer, back.jpg",
    "013-Palette of King Narmer, front.jpg",
    "014-Statues of votive figures.jpg",
    "015-Seated scribe.jpg",
    "016-Standard of Ur, Peace.jpg",
    "016-Standard of Ur, War.jpg",
    "017-Great Pyramids plan.jpg",
    "017-Great Pyramids with Sphinx.jpg",
    "018-King Menkaura and queen.jpg",
    "019-The Code of Hammurabi.jpg",
    "020-Hypostyle Hall.jpg",
    "020-Temple of Amun-Re plan.jpg",
    "020-Temple of Amun-Re.jpg",
    "021-Kneeling statue of Hatshepsut.jpg",
    "021-Mortuary temple of Hatshepsut.jpg",
    "022-Akhenaton, Nefertiti, and three daughters.jpg",
    "023-Tutankhamun's innermost coffin.jpg",
    "024-Last judgment of Hu-Nefer.jpg",
    "025-Lamassu.jpg",
    "026-Athenian agora site plan.jpg",
    "027-Anavysos Kouros.jpg",
    "028-Peplos Kore.jpg",
    "029-Sarcophagus of the Spouses.jpg",
    "030-Apadana stairway.jpg",
    "030-Apadana.jpg",
    "031-Apollo.jpg",
    "031-Temple of Minerva elevation.jpg",
    "031-Temple of Minerva plan.jpg",
    "032-Tomb of the Triclinium.jpg",
    "033-Niobides Krater-1.jpg",
    "033-Niobides Krater-2.jpg",
    "034-Doryphoros.jpg",
    "035-Acropolis plan.jpg",
    "035-Helios, horses, and Dionysus.jpg",
    "035-Parthenon.jpg",
    "035-Plaque of the Ergastines.jpg",
    "035-Temple of Athena Nike.jpg",
    "035-Victory adjusting her sandal.jpg",
    "036-Grave stele of Hegeso.jpg",
    "037-Winged Victory of Samothrace.jpg",
    "038-Athena.jpg",
    "038-Great Altar of Zeus and Athena plan.jpg",
    "038-Great Altar of Zeus and Athena.jpg",
    "039-Atrium.jpg",
    "039-Frescoes.jpg",
    "039-House of the Vettii plan.jpg",
    "040-Alexander Mosaic.jpg",
    "041-Seated boxer.jpg",
    "042-Head of a Roman patrician.jpg",
    "043-Augustus of Prima Porta.jpg",
    "044-Colosseum-1.jpg",
    "044-Colosseum-2.jpg",
    "045-Basilica Ulpia.jpg",
    "045-Column of Trajan.jpg",
    "045-Forum of Trajan.jpg",
    "045-Trajan markets.jpg",
    "046-Pantheon-1.jpg",
    "046-Pantheon-2.jpg",
    "047-Ludovisi battle Sarcophagus.jpg",
    "048-Good Shepherd fresco of Catacomb of Priscilla.jpg",
    "048-Greek Chapel.jpg",
    "048-Orant fresco.jpg",
    "049-Santa Sabina plan.jpg",
    "049-Santa Sabina-1.jpg",
    "049-Santa Sabina-2.jpg",
    "050-Jacob Wresting the Angel.jpg",
    "050-Rebecca and Eliezer at the Well.jpg",
    "051-Justinian panel.jpg",
    "051-San Vitale plan.jpg",
    "051-San Vitale-1.jpg",
    "051-San Vitale-2.jpg",
    "051-Theodora panel.jpg",
    "052-Hagia Sophia-1.jpg",
    "052-Hagia Sophia-2.jpg",
    "052-Haigia Sophia plan.jpg",
    "053-Merovingian looped fibulae.jpg",
    "054-Virgin and Child between Saints Theodore and George.jpg",
    "055-St. Luke incipit page from Lindisfarne Gospels.jpg",
    "055-St. Luke portrait page from Lindisfarne Gospels.jpg",
    "055-St. Matthew, cross-carpet page from Lindisfarne Gospels.jpg",
    "056-Great Mosque arches.jpg",
    "056-Great Mosque at Cordoba detail.jpg",
    "056-Great Mosque at Cordoba plan.jpg",
    "056-Great Mosque at Cordoba-1.jpg",
    "056-Great Mosque at Cordoba-2.jpg",
    "057-Pyxis of al-Mughira.jpg",
    "058-Church of Sainte-Foy-2.jpg",
    "058-Church of Sainte-Foy.jpg",
    "058-Reliquary of Sainte-Foy.jpg",
    "058-The Last Judgement.jpg",
    "059-Cavalry attack of Bayeux Tapestry.jpg",
    "059-First meal of Bayeux Tapestry.jpg",
    "060-Chartres Cathedral plan.jpg",
    "060-Chartres Cathedral-1.jpg",
    "060-Chartres Cathedral-2.jpg",
    "060-Chartres Cathedral-3.jpg",
    "060-Great Portal of the West Facade of Chartres Cathedral.jpg",
    "060-Notre Dame de la Belle Verriere window of Chartres Cathedral.jpg",
    "061-Dedication Page with Blanche of Castile and King Louis IX of France from Bibles moralisees.jpg",
    "061-Scenes from the Apocalypse from Bibles moralisees.jpg",
    "062-Rottgen Pieta.jpg",
    "063-Arena Chapel-1.jpg",
    "063-Arena Chapel-2.jpg",
    "063-Lamentation of Arena Chapel.jpg",
    "064-Preparation for Passover from Golden Haggadah.jpg",
    "064-Scenes of Liberation from Golden Haggadah.jpg",
    "064-The Plagues of Egypt from Golden Haggadah.jpg",
    "065-Alhambra plan.jpg",
    "065-Alhambra.jpg",
    "065-Court of the Lions from Alhambra.jpg",
    "065-Hall of the Sisters from Alhambra.jpg",
    "066-Annunciation Triptych.jpg",
    "067-Pazzi Chapel-1.jpg",
    "067-Pazzi Chapel-2.jpg",
    "068-The Arnolfini Portrait.jpg",
    "069-David.jpg",
    "070-Palazzo Rucellai.jpg",
    "071-Madonna and Child with Two Angels.jpg",
    "072-Birth of Venus.jpg",
    "073-Last Supper.jpg",
    "074-Adam and Eve.jpg",
    "075-Sistine Chapel-1.jpg",
    "075-Sistine Chapel-2.jpg",
    "075-The Delphic Sibyl from Sistine Chapel.jpg",
    "075-The Flood from Sistine Chapel.jpg",
    "076-School of Athens.jpg",
    "077-Isenheim altarpiece, closed.jpg",
    "077-Isenheim altarpiece, open.jpg",
    "078-Entombment of Christ.jpg",
    "079-Allegory of Law and Grace.jpg",
    "080-Venus of Urbino.jpg",
    "081-Frontispiece of the Codex Mendoza.jpg",
    "082-Il Gesu-1.jpg",
    "082-Il Gesu-2.jpg",
    "082-Triumph of the Name of Jesus.jpg",
    "083-Hunters in the Snow.jpg",
    "084-Mosque of Selim II plan.jpg",
    "084-Mosque of Selim II-1.jpg",
    "084-Mosque of Selim II-2.jpg",
    "085-Calling of Saint Matthew.jpg",
    "086-Henri IV Receives the Portrait of Marie de' Medici.jpg",
    "087-Self-Portrait with Saskia.jpg",
    "088-San Carlo alle Quattro Fontane plan.jpg",
    "088-San Carlo alle Quattro Fontane-1.jpg",
    "088-San Carlo alle Quattro Fontane-2.jpg",
    "089-Church of Santa Maria della Vittoria.jpg",
    "089-Cornaro Chapel.jpg",
    "089-Ecstasy of Saint Teresa.jpg",
    "090-Angel with Arquebus, Asiel Timor Dei.jpg",
    "091-Las Meninas.jpg",
    "092-Woman Holding a Balance.jpg",
    "093-Courtyard of The Palace at Versailles.jpg",
    "093-Gardens of the Palace at Versailles.jpg",
    "093-Hall of Mirrors of The Palace at Versailles.jpg",
    "093-The Palace at Versailles-1.jpg",
    "093-The Palace at Versailles-2.jpg",
    "094-Screen with the Siege of Belgrade and hunting scene-front.jpg",
    "094-Screen with the Siege of Belgrade and hunting scene-reverse.jpg",
    "095-The Virgin of Guadalupe.jpg",
    "096-Fruit and Insects.jpg",
    "097-Spaniard and Indian Produce a Mestizo.jpg",
    "098-The Tete a Tete.jpg",
    "099-Portrait of Sor Juana Ines de la Cruz.jpg",
    "100-A Philosopher Giving a Lecture on the Orrery.jpg",
    "101-The Swing.jpg",
    "102-Monticello plan.jpg",
    "102-Monticello.jpg",
    "103-The Oath of the Horatii.jpg",
    "104-George Washington.jpg",
    "105-Self-Portrait.jpg",
    "106-And There's Nothing to Be Done.jpg",
    "107-La Grande Odalisque.jpg",
    "108-Liberty Leading the People.jpg",
    "109-The Oxbow.jpg",
    "110-Still Life in Studio.jpg",
    "111-Slave Ship.jpg",
    "112-Central Lobby of Palace of Westminster.jpg",
    "112-Palace of Westminster.jpg",
    "112-Westminster Hall of Palace of Westminster.jpg",
    "113-The Stone Breakers.jpg",
    "114-Nadar Raising Photography to the Height of Art.jpg",
    "115-Olympia.jpg",
    "116-The Saint-Lazare Station.jpg",
    "117-The Horse in Motion.jpg",
    "118-The Valley of Mexico from the Hillside of Santa Isabel.jpg",
    "119-The Burghers of Calais.jpg",
    "120-The Starry Night.jpg",
    "121-The Coiffure.jpg",
    "122-The Scream.jpg",
    "123-Where Do We Come From What Are We Where Are We Going.jpg",
    "124-Carson, Pirie, Scott and Company Building plan.jpg",
    "124-Carson, Pirie, Scott and Company Building.jpg",
    "124-Detail of Carson, Pirie, Scott and Company Building.jpg",
    "125-Mont Sainte-Victoire.jpg",
    "126-Les Demoiselles d'Avignon.jpg",
    "127-The Steerage.jpg",
    "128-The Kiss, Gustav Klimt.jpg",
    "129-The Kiss, Constantin Brancusi.jpg",
    "131-The Portuguese.jpg",
    "132-Goldfish.jpg",
    "133-Improvisation 28 (second version).jpg",
    "134-Self-Portrait as a Soldier.jpg",
    "135-Memorial Sheet for Karl Liebknecht.jpg",
    "136-Villa Savoye-1.jpg",
    "136-Villa Savoye-2.jpg",
    "137-Composition with Red, Blue and Yellow.jpg",
    "138-Illustration from The Results of the First Five-Year Plan.jpg",
    "139-Object (Le Dejeuner en fourrure).jpg",
    "140-Fallingwater site plan.jpg",
    "140-Fallingwater-1.jpg",
    "140-Fallingwater-2.jpg",
    "141-The Two Fridas.jpg",
    "142-The Migration of the Negro, Panel no.49.jpg",
    "143-The Jungle.jpg",
    "144-Dream of a Sunday Afternoon in the Alameda Park.jpg",
    "145-Fountain.jpg",
    "146-Woman, I.jpg",
    "147-Seagram Building.jpg",
    "148-Marilyn Diptych.jpg",
    "149-Narcissus Garden.jpg",
    "149-The Bay.jpg",
    "150-Lipstick (Ascending) on Caterpillar Tracks.jpg",
    "151-Spiral Jetty.jpg",
    "152-House in New Castle County-1.jpg",
    "152-House in New Castle County-2.jpg",
    "153-Chavin de Huantar plan.jpg",
    "153-Lanzon Stela plan.jpg",
    "153-Nose ornament.jpg",
    "153-Relief sculpture.jpg",
    "154-Mesa Verde cliff dwellings.jpg",
    "155-Lintel 25, Structure 23 of Yaxchilan.jpg",
    "155-Structure 33 of Yaxchilan.jpg",
    "155-Structure 40 of Yaxchilan.jpg",
    "156-Great Serpent Mound.jpg",
    "157-Calendar Stone of Templo Mayor.jpg",
    "157-Olmec-style mask of Templo Mayor.jpg",
    "157-Templo Mayor.jpg",
    "157-The Coyolxauhqui Stone of Templo Mayor.jpg",
    "158-Ruler's feather headdress.jpg",
    "159-City of Cusco plan.jpg",
    "159-Curved Inka wall of Qorikancha with Santo Domingo.jpg",
    "159-Walls at Saqsa Waman of City of Cusco.jpg",
    "160-Maize cobs.jpg",
    "161-City of Machu Picchu.jpg",
    "161-Intihuatana Stone of City of Machu Picchu.jpg",
    "161-Observatory of City of Machu Picchu.jpg",
    "162-All-T'oqapu tunic.jpg",
    "163-Bandolier bag.jpg",
    "164-Transformation mask, closed.jpg",
    "164-Transformation mask, open.jpg",
    "165-Painted elk hide.jpg",
    "166-Black-on-black ceramic vessel.jpg",
    "167-Circular wall of Great Zimbabwe.jpg",
    "167-Conical tower of Great Zimbabwe.jpg",
    "168-Great Mosque of Djenne.jpg",
    "168-Monday market at the Great Mosque of Djenne.jpg",
    "169-Contextual photograph Oba of Benin.jpg",
    "169-Wall plaque, from Oba's palace.jpg",
    "170-Contextual photograph Golden Stool.jpg",
    "170-Golden Stool.jpg",
    "171-Contextual photograph Ndop.jpg",
    "171-Ndop.jpg",
    "172-Power figure.jpg",
    "173-Female mask.jpg",
    "174-Contextual photograph Mblo.jpg",
    "174-Mblo.jpg",
    "175-Bundu mask.jpg",
    "175-Contextual photograph Bundu mask.jpg",
    "176-Ikenga.jpg",
    "177-Contextual photograph memorial board.jpg",
    "177-Memory board.jpg",
    "178-Aka elephant mask.jpg",
    "178-Contextual photograph Aka elephant mask.jpg",
    "179-Reliquary figure.jpg",
    "180-Veranda post of enthroned king and senoir wife.jpg",
    "181-Great Temple of Petra.jpg",
    "181-Petra.jpg",
    "181-Treasury of Petra.jpg",
    "182-Buddha at Bamiyan-1.jpg",
    "182-Buddha at Bamiyan-2.jpg",
    "183-Gathering at the Kaaba.jpg",
    "183-Kaaba-1.jpg",
    "183-The Kaaba-2.jpg",
    "184-Jowo Rinpoche.jpg",
    "185-Dome of the Rock-1.jpg",
    "185-Dome of the Rock-2.jpg",
    "186-Courtyard of Great Mosque at Isfahan.jpg",
    "186-Great Mosque at Isfahan-1.jpg",
    "186-Great Mosque at Isfahan-2.jpg",
    "186-Mihrab of Great Mosque at Isfahan.jpg",
    "187-Folio from a Qur'an.jpg",
    "188-Basin.jpg",
    "189-Bahram Gur Fights the Karg.jpg",
    "189-Buddha of Borobudur Temple.jpg",
    "190-The Court of Gayumars.jpg",
    "191-The Ardabil Carpet.jpg",
    "192-Detail of Great Stupa at Sanchi.jpg",
    "192-Great Stupa at Sanchi plan.jpg",
    "192-Great Stupa at Sanchi.jpg",
    "192-North Gate of Great Stupa at Sanchi.jpg",
    "193-Terra cotta warriors-1.jpg",
    "193-Terra cotta warriors-2.jpg",
    "194-Funeral banner of Xin Zhui.jpg",
    "195-Detail of Longmen caves-1.jpg",
    "195-Detail of Longmen caves-2.jpg",
    "195-Longmen caves.jpg",
    "196-Gold and jade crown.jpg",
    "197-Gate of Todai-ji.jpg",
    "197-Great Buddha of Todai-ji.jpg",
    "197-Nio guardian statue of Todai-ji-1.jpg",
    "197-Nio guardian statue of Todai-ji-2.jpg",
    "197-Todai-ji.jpg",
    "198-Borobudur Temple.jpg",
    "198-Detail of Borobudur Temple.jpg",
    "199-Angkor site plan.jpg",
    "199-Angkor Wat plan.jpg",
    "199-Angkor Wat.jpg",
    "199-Churning of the Ocean of Milk of Angkor Wat.jpg",
    "199-Jayavarman Vll as Buddha of Angkor Wat.jpg",
    "199-South Gate of Angkor Thom.jpg",
    "200-Detail of Lakshmana Temple-1.jpg",
    "200-Detail of Lakshmana Temple-2.jpg",
    "200-Lakshmana Temple plan.jpg",
    "200-Lakshmana Temple.jpg",
    "201-Travelers among Mountains and Streams.jpg",
    "202-Shiva as Lord of Dance.jpg",
    "203-Detail of Night Attack on the Sanjo Palace.jpg",
    "203-Night Attack on the Sanjo Palace.jpg",
    "204-The David Vases.jpg",
    "205-Portrait of Sin Sukju.jpg",
    "206-Forbidden City plan.jpg",
    "206-Forbidden City.jpg",
    "206-Front Gate of Forbidden City.jpg",
    "206-Hall of Supreme Harmony.jpg",
    "206-The Palace of Tranquility and Longevity.jpg",
    "207-Ryoan-ji plan.jpg",
    "207-Ryoan-ji, dry garden.jpg",
    "207-Ryoan-ji, wet garden.jpg",
    "208-Jahangir Preferring a Sufi Shaikh to Kings.jpg",
    "209-Taj Mahal-1.jpg",
    "209-Taj Mahal-2.jpg",
    "210-White and Red Plum Blossom-2.jpg",
    "210-White and Red Plum Blossoms-1.jpg",
    "211-Under the Waves off Kanagawa.jpg",
    "212-Chairman Mao en Route to Anyuan.jpg",
    "213-Nan Madol-1.jpg",
    "213-Nan Madol-2.jpg",
    "214-Moai on platform.jpg",
    "215-'Ahu 'ula.jpg",
    "216-Contextual image staff god.jpg",
    "216-Detail of Staff god.jpg",
    "216-Staff god.jpg",
    "217-Female deity.jpg",
    "218-Buk.jpg",
    "219-Hiapo.jpg",
    "220-Tamati Waka Nene.jpg",
    "221-Navigation chart.jpg",
    "222-Malagan display.jpg",
    "222-Malagan mask.jpg",
    "223-Presentation of Fijian mats to Queen Elizabeth II.jpg",
    "224-The Gates-1.jpg",
    "224-The Gates-2.jpg",
    "225-Detail of Viet Veterans Memorial.jpg",
    "225-Vietnam Veterans Memorial.jpg",
    "226-Horn Players.jpg",
    "227-Summer Trees.jpg",
    "228-Androgyne III.jpg",
    "229-A Book from the Sky.jpg",
    "230-Pink Panther.jpg",
    "231-Untitled (#228).jpg",
    "232-Dancing at the Louvre.jpg",
    "233-Trade (Gifts for Trading Land with White People).jpg",
    "234-Earth's Creation.jpg",
    "235-Rebellious Silence.jpg",
    "236-No Crying Allowed in the Barbershop.jpg",
    "237-Corned Beef 2000.jpg",
    "238-Electronic Superhighway.jpg",
    "239-The Crossing.jpg",
    "240-Guggenheim Museum Bilbao site plan.jpg",
    "240-Guggenheim Museum Bilbao-1.jpg",
    "240-Guggenheim Museum Bilbao-2.jpg",
    "241-Pure Land.jpg",
    "242-Lying with the Wolf.jpg",
    "243-Darkytown Rebellion.jpg",
    "244-The Swing (after Fragonard).jpg",
    "245-Old Man's Cloth.jpg",
    "246-Stadia II.jpg",
    "247-Preying Mantra.jpg",
    "248-Shibboleth.jpg",
    "249-MAXXI National Museum of XXI Century Arts-1.jpg",
    "249-MAXXI National Museum of XXI Century Arts.jpg",
    "250-Kui Hua Zi.jpg",
];
const APAH_IMG_LIST = {};

imageFilesRaw.forEach(filename => {
    // 提取开头的数字，例如从 "008-Stonehenge-1.jpg" 提取 "8"
    const match = filename.match(/^(\d+)/);
    if (match) {
        const id = parseInt(match[1]);
        if (!APAH_IMG_LIST[id]) {
            APAH_IMG_LIST[id] = [];
        }
        APAH_IMG_LIST[id].push(filename);
    }
});
